name: Commit and Push From Action
description: This is an action which can commit and push the files generated in action back to repository
inputs:
  git_username:
    description: username from which commit is to be made
    required: true
    default: codebot
  git_email:
    description: email from which commit is to be made
    required: true
    default: codebot
  branch:
    description: branch on which commit is to be made
    required: true
    default: main
  commit_message:
    description: commit message for the commit
    required: true
    default: commit from the bot
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.git_username }}
    - ${{ inputs.git_email }}
    - ${{ inputs.branch }}
    - ${{ inputs.commit_message }}
branding:
  icon: git-pull-request
  color: orange